In [12]:
import pandas as pd 
import numpy as np

In [13]:
df = pd.read_csv('dataset/synthetic_logs.csv')
df.head()

,timestamp,source,log_message,target_label,complexity
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert

In [14]:
df.source.unique()

array(['ModernCRM', 'AnalyticsEngine', 'ModernHR', 'BillingSystem',
       'ThirdPartyAPI', 'LegacyCRM'], dtype=object)

In [15]:
df.target_label.unique()

array(['HTTP Status', 'Critical Error', 'Security Alert', 'Error',
       'System Notification', 'Resource Usage', 'User Action',
       'Workflow Error', 'Deprecation Warning'], dtype=object)

In [ ]:
from sentence_transformers import SentenceTransformer
from sklearn.cluster import DBSCAN
import numpy as np 

# Load pretrained sentence transformer model 
model = SentenceTransformer('all-MiniLM-L6-v2')

# Generate Embeddings 
embeddings = model.encode(df['log_message'].to_list())

# Perform DBSCAN
dbscan = DBSCAN(eps = 0.2, min_samples=1, metric = 'cosine')
clusters = dbscan.fit_predict(embeddings)

# Add cluster labels to the DataFrame
df['cluster'] = clusters

In [17]:
df.head()

,timestamp,source,log_message,target_label,complexity,cluster
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert,0
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert,1
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert,2
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert,0
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert,0

In [18]:
df.cluster.unique()

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135])

In [19]:
df[df.cluster == 1]

,timestamp,source,log_message,target_label,complexity,cluster
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert,1
10,8/9/2025 18:58,ModernCRM,Email server encountered a sending fault,Error,bert,1
217,1/22/2025 5:45,BillingSystem,Mail service encountered a delivery glitch,Error,bert,1
248,5/2/2025 23:04,ModernHR,Service disruption caused by email sending error,Critical Error,bert,1
265,3/30/2025 23:53,ModernCRM,Email system had a problem sending emails,Error,bert,1
361,11/19/2025 23:06,BillingSystem,Email service experienced a sending issue,Error,bert,1
450,10/27/2025 5:59,ThirdPartyAPI,Email delivery system encountered an error,Error,bert,1
477,12/2/2025 10:30,AnalyticsEngine,Email transmission error caused service impact,Critical Error,bert,1
570,11/7/2025 18:08,ThirdPartyAPI,Email service impacted by sending failure,Critical Error,bert,1
678,4/28/2025 15:13,AnalyticsEngine,Email delivery problem affected system,Critical Error,bert,1
695,6/30/2025 12:46,ThirdPartyAPI,Service outage due to email delivery problem,Critical Error,bert,1
816,7/9/2025 9:38,BillingSystem,Error in email delivery affected service,Critical Error,bert,1
926,2/17/2025 8:01,ModernCRM,Email service suffered a delivery failure,Error,bert,1
1011,2/9/2025 17:04,AnalyticsEngine,Error in email sending impacted service,Critical Error,bert,1
1018,2/16/2025 15:02,BillingSystem,Mail service impacted by delivery glitch,Critical Error,bert,1
1046,11/26/2025 22:54,AnalyticsEngine,Email service had a difficulty delivering mess...,Error,bert,1
1058,10/24/2025 5:37,AnalyticsEngine,Email system failed to deliver emails,Error,bert,1
1082,5/17/2025 11:20,ModernHR,Delivery failure impacted email services,Critical Error,bert,1
1151,6/17/2025 15:13,ThirdPartyAPI,Mail service was unable to send emails,Error,bert,1
1176,10/1/2025 12:27,AnalyticsEngine,Email provider faced a delivery challenge,Error,bert,1
1189,2/9/2025 6:15,ModernCRM,Service issue caused by email delivery error,Critical Error,bert,1
1359,8/18/2025 15:58,ModernCRM,Email system down due to sending error,Critical Error,bert,1
1414,6/22/2025 23:07,ModernCRM,Email system encountered a sending error,Error,bert,1
1427,10/26/2025 20:25,ModernHR,Email provider had trouble sending emails,Error,bert,1
1453,9/11/2025 1:18,BillingSystem,Mail delivery error impacted email service,Critical Error,bert,1
1554,3/2/2025 9:21,ModernCRM,Email system had a difficulty sending messages,Error,bert,1
1567,5/11/2025 11:17,ThirdPartyAPI,Email system affected by delivery failure,Critical Error,bert,1
1582,9/10/2025 9:27,BillingSystem,Email delivery failure resulted in service issue,Critical Error,bert,1
1860,6/26/2025 1:08,BillingSystem,Email provider experienced a mail delivery issue,Error,bert,1
1867,10/6/2025 11:04,ModernCRM,Email service had a sending malfunction,Error,bert,1
1901,9/22/2025 2:52,ThirdPartyAPI,Email service experienced a mail sending issue,Error,bert,1
1972,3/12/2025 3:48,ThirdPartyAPI,Delivery issue with email service caused outage,Critical Error,bert,1
2049,10/1/2025 22:07,AnalyticsEngine,Email server experienced a delivery problem,Error,bert,1
2165,4/4/2025 16:11,ThirdPartyAPI,Email server had trouble transmitting emails,Error,bert,1
2281,3/23/2025 20:12,ThirdPartyAPI,Mail delivery issue caused service disruption,Critical Error,bert,1
2284,10/4/2025 18:15,BillingSystem,Email service down due to transmission issue,Critical Error,bert,1
2312,3/9/2025 21:16,ModernHR,Email service faced a delivery obstacle,Error,bert,1
2340,3/26/2025 8:10,ModernCRM,Service outage due to email transmission error,Critical Error,bert,1
2408,11/11/2025 11:52,BillingSystem,Email service affected by failed transmission,Critical Error,bert,1

In [20]:
cluster_counts = df['cluster'].value_counts()
large_clusters = cluster_counts[cluster_counts > 10].index

for cluster in large_clusters:
    print(f'Cluster {cluster}:')

    print(df[df['cluster'] == cluster]['log_message'].head(5).to_string(index = False))

    print()

Cluster 0:
nova.osapi_compute.wsgi.server [req-b9718cd8-f6...
nova.osapi_compute.wsgi.server [req-4895c258-b2...
nova.osapi_compute.wsgi.server [req-ee8bc8ba-92...
nova.osapi_compute.wsgi.server [req-f0bffbc3-5a...
nova.osapi_compute.wsgi.server [req-2bf7cfee-a2...

Cluster 5:
nova.compute.claims [req-a07ac654-8e81-416d-bfb...
nova.compute.claims [req-d6986b54-3735-4a42-907...
nova.compute.claims [req-72b4858f-049e-49e1-b31...
nova.compute.claims [req-5c8f52bd-8e3c-41f0-95a...
nova.compute.claims [req-d38f479d-9bb9-4276-968...

Cluster 11:
User User685 logged out.
 User User395 logged in.
 User User225 logged in.
User User494 logged out.
 User User900 logged in.

Cluster 13:
Backup started at 2025-05-14 07:06:55.
Backup started at 2025-02-15 20:00:19.
  Backup ended at 2025-08-08 13:06:23.
Backup started at 2025-11-14 08:27:43.
Backup started at 2025-12-09 10:19:11.

Cluster 7:
Multiple bad login attempts detected on user 85...
Multiple login failures occurred on user 9052 a...
  User 7153 made multiple incorrect login attempts
  User 8300 made multiple incorrect login attempts
Multiple login failures were detected for user ...

Cluster 8:
Backup completed successfully.
Backup completed successfully.
Backup completed successfully.
Backup completed successfully.
Backup completed successfully.

Cluster 21:
System updated to version 3.9.1.
System updated to version 5.5.4.
System updated to version 4.7.4.
System updated to version 3.7.7.
System updated to version 2.6.2.

Cluster 3:
         Shard 6 replication task ended in failure
Data replication task for shard 14 did not comp...
         Data replication task failed for shard 17
            Replication of data to shard 14 failed
Data replication task for shard 6 did not complete

Cluster 4:
File data_6169.csv uploaded successfully by use...
File data_3847.csv uploaded successfully by use...
File data_7366.csv uploaded successfully by use...
File data_1206.csv uploaded successfully by use...
File data_1503.csv uploaded successfully by use...

Cluster 17:
Denied access attempt on restricted account Acc...
Unauthorized login attempt on protected account...
   Account Account9437 blocked due to failed login
Account Account7999 access denied due to login ...
Invalid login attempt made on secured account A...

Cluster 32:
Disk cleanup completed successfully.
Disk cleanup completed successfully.
Disk cleanup completed successfully.
Disk cleanup completed successfully.
Disk cleanup completed successfully.

Cluster 6:
   Critical system unit error: unit ID Component55
System component malfunction: component ID Comp...
Critical system element is down: element ID Com...
Essential system part malfunction: part ID Comp...
Failure occurred in critical system component: ...

Cluster 16:
System reboot initiated by user User243.
System reboot initiated by user User471.
System reboot initiated by user User216.
System reboot initiated by user User639.
System reboot initiated by user User819.

Cluster 20:
   User 7662 tried to bypass API security measures
User 2367 failed to provide valid API access cr...
        User 3569 made an unauthorized API request
Unauthorized user 2968 tried to access restrict...
User 2186 attempted to access API without prope...

Cluster 9:
Account with ID 5351 created by User634.
Account with ID 7813 created by User373.
Account with ID 9827 created by User965.
Account with ID 2520 created by User546.
Account with ID 2300 created by User964.

Cluster 1:
  Email service experiencing issues with sending
        Email server encountered a sending fault
      Mail service encountered a delivery glitch
Service disruption caused by email sending error
       Email system had a problem sending emails

Cluster 10:
nova.compute.resource_tracker [req-addc1839-2ed...
nova.compute.resource_tracker [req-addc1839-2ed...
nova.compute.resource_tracker [req-addc1839-2ed...
nova.compute.resource_tracker [req-addc1839-2ed...
nova.compute.resource_tracker [req-addc1839-2ed...

Cluster 34:
Abnormal behavior found on server 10, possible ...
   Security alert: suspicious activity on server 1
Anomalous activity identified on server 23, sec...
Server 27 experienced potential security incide...
Server 36 experienced potential security incide...

Cluster 14:
   Detection of multiple disk faults in RAID setup
  RAID array suffered multiple hard drive failures
      RAID array experienced multiple disk crashes
Multiple hard drive issues in RAID configuratio...
Identification of multiple faulty disks in RAID...

Cluster 53:
 Module X experienced an invalid data format issue
        Input format mismatch occurred in module X
Module X reported an error in input format vali...
Module X failed to process input due to formatt...
Input data format in module X was invalid or co...

Cluster 52:
Service health check was not successful because...
Invalid SSL certificate resulted in a failed se...
Service health check failure was due to an inva...
An issue with the SSL certificate caused the se...
Service health check failure was caused by an e...

Cluster 18:
Boot process terminated unexpectedly due to ker...
System encountered kernel panic during initiali...
    Boot process was stopped by kernel malfunction
System encountered kernel failure during bootup...
          Boot sequence failed due to kernel panic

Cluster 42:
User 5127 has escalated admin privileges withou...
            User 9745 has escalated to admin level
     User 8483 escalated privileges to admin level
            User 1987 has escalated to admin level
     User 8395 escalated privileges to admin level

Cluster 25:
         System configuration is no longer valid
Configuration is corrupted throughout the system
     Cross-system configuration failure occurred
     System configuration is experiencing errors
        Configuration malfunction is system-wide

Cluster 59:
Potential security threat: Admin privilege esca...
    Admin privilege escalation alert for user 2893
    Admin privilege escalation alert for user 8532
Potential security threat: Admin privilege esca...
Warning: Potential admin privilege escalation f...

Cluster 26:
        Privilege elevation detected for user 5038
Elevation of admin privileges detected for user...
Elevation of admin privileges detected for user...
User 6069 has been granted elevated admin privi...
   Admin privilege elevation warning for user 7574

In [32]:
import re
def classify_with_regex(log_message):
    regex_patterns = {
        r"User User\d+ logged (in|out).": "User Action",
        r"Backup (started|ended) at .*": "System Notification",
        r"Backup completed successfully.": "System Notification",
        r"System updated to version .*": "System Notification",
        r"File .* uploaded successfully by user .*": "System Notification",
        r"Disk cleanup completed successfully.": "System Notification",
        r"System reboot initiated by user .*": "System Notification",
        r"Account with ID .* created by .*": "User Action"
    }
    for pattern, label in regex_patterns.items():
        if re.search(pattern, log_message, re.IGNORECASE):
            return label
    return None

In [33]:
classify_with_regex("User User494 logged in.")

'User Action'

In [34]:
df['regex_label'] = df['log_message'].apply(classify_with_regex)

In [35]:
df

,timestamp,source,log_message,target_label,complexity,cluster,regex_label
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert,0,None
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert,1,None
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert,2,None
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert,0,None
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert,0,None
...,...,...,...,...,...,...,...
2405,2025-08-13 07:29:25,ModernHR,nova.osapi_compute.wsgi.server [req-96c3ec98-2...,HTTP Status,bert,0,None
2406,1/11/2025 5:32,ModernHR,User 3844 account experienced multiple failed ...,Security Alert,bert,7,None
2407,2025-08-03 03:07:47,ThirdPartyAPI,nova.metadata.wsgi.server [req-b6d4a270-accb-4...,HTTP Status,bert,0,None
2408,11/11/2025 11:52,BillingSystem,Email service affected by failed transmission,Critical Error,bert,1,None
2409,12/25/2025 13:21,AnalyticsEngine,Repeated failed login attempts occurred for us...,Security Alert,bert,7,None

In [36]:
df.regex_label.unique()

array([None, 'System Notification', 'User Action'], dtype=object)

In [38]:
df_non_regex = df[df['regex_label'].isnull()].copy()

df_non_regex.shape

(1910, 7)

In [39]:
print(df_non_regex['target_label'].value_counts()[df_non_regex['target_label'].value_counts() <= 5].index.tolist())

['Workflow Error', 'Deprecation Warning']

In [41]:
df['regex_label'] = df['log_message'].apply(classify_with_regex)

df[df.regex_label.notnull()]

,timestamp,source,log_message,target_label,complexity,cluster,regex_label
7,10/11/2025 8:44,ModernHR,File data_6169.csv uploaded successfully by us...,System Notification,regex,4,System Notification
14,1/4/2025 1:43,ThirdPartyAPI,File data_3847.csv uploaded successfully by us...,System Notification,regex,4,System Notification
15,5/1/2025 9:41,ModernCRM,Backup completed successfully.,System Notification,regex,8,System Notification
18,2/22/2025 17:49,ModernCRM,Account with ID 5351 created by User634.,User Action,regex,9,User Action
27,9/24/2025 19:57,ThirdPartyAPI,User User685 logged out.,User Action,regex,11,User Action
...,...,...,...,...,...,...,...
2376,6/27/2025 8:47,ModernCRM,System updated to version 2.0.5.,System Notification,regex,21,System Notification
2381,9/5/2025 6:39,ThirdPartyAPI,Disk cleanup completed successfully.,System Notification,regex,32,System Notification
2394,4/3/2025 13:13,ModernHR,Disk cleanup completed successfully.,System Notification,regex,32,System Notification
2395,5/2/2025 14:29,ThirdPartyAPI,Backup ended at 2025-05-06 11:23:16.,System Notification,regex,13,System Notification
2403,10/1/2025 1:31,ModernCRM,Backup completed successfully.,System Notification,regex,8,System Notification

In [42]:
df_non_legacy = df_non_regex[df_non_regex.source != 'LegacyCRM']

df_non_legacy.source.unique()

array(['ModernCRM', 'AnalyticsEngine', 'ModernHR', 'BillingSystem',
       'ThirdPartyAPI'], dtype=object)

In [43]:
filtered_embeddings = model.encode(df_non_legacy['log_message'].tolist())

filtered_embeddings[:2]

array([[-1.02939680e-01,  3.35459374e-02, -2.20260732e-02,
         1.55095884e-03, -9.86917876e-03, -1.78956285e-01,
        -6.34410381e-02, -6.01761863e-02,  2.81108897e-02,
         5.99619523e-02, -1.72618572e-02,  1.43367227e-03,
        -1.49560034e-01,  3.15280934e-03, -5.66030927e-02,
         2.71685533e-02, -1.49890659e-02, -3.54037359e-02,
        -3.62936370e-02, -1.45410346e-02, -5.61490422e-03,
         8.75539035e-02,  4.55121100e-02,  2.50963457e-02,
         1.00187417e-02,  1.24267405e-02, -1.39923543e-01,
         7.68696070e-02,  3.14095467e-02, -4.15254897e-03,
         4.36903648e-02,  1.71250012e-02, -8.00950974e-02,
         5.74006252e-02,  1.89091749e-02,  8.55261460e-02,
         3.96398455e-02, -1.34371787e-01, -1.44362182e-03,
         3.06711439e-03,  1.76854074e-01,  4.44887998e-03,
        -1.69274528e-02,  2.24266630e-02, -4.35050204e-02,
         6.09029876e-03, -9.98174399e-03, -6.23972565e-02,
         1.07372403e-02, -6.04899880e-03, -7.14660734e-02,
        -8.45806114e-03, -3.18020098e-02, -1.00518398e-01,
         2.25815616e-04, -1.89341325e-02, -3.17794532e-02,
         4.00861278e-02,  2.19177585e-02, -2.59528346e-02,
         5.84524982e-02, -8.12509730e-02,  2.12029088e-02,
        -5.02687469e-02,  1.32057341e-02,  1.32674980e-03,
         2.27063224e-02, -3.45793851e-02,  3.91547233e-02,
        -2.09433641e-02,  3.24817770e-03,  4.43960615e-02,
        -9.85357538e-02, -2.88894400e-02, -6.85029570e-03,
         5.38818724e-02,  6.46110475e-02, -2.45059654e-02,
         9.21828002e-02, -7.49868974e-02,  1.23995496e-02,
        -1.00026608e-01, -4.64910418e-02,  6.01570681e-02,
        -2.46480871e-02, -7.08075985e-02, -2.77270377e-02,
         9.72611234e-02,  3.85841280e-02, -1.44292694e-02,
        -7.46872567e-04, -1.04305102e-02, -1.61843169e-02,
         4.43627685e-02,  9.25993267e-03,  7.14165866e-02,
         6.37916625e-02,  4.94930893e-02, -6.02567494e-02,
         4.04805951e-02, -3.42860445e-02, -1.93881486e-02,
         6.61233813e-02,  6.01589233e-02,  1.09371226e-02,
        -5.38630551e-03,  1.44580062e-02,  9.25430506e-02,
        -3.14563178e-02, -1.84351187e-02,  9.91878845e-03,
        -1.85574591e-02,  1.31279696e-03,  2.27365217e-05,
         2.02732906e-03,  2.75256224e-02, -4.81927432e-02,
         5.42825907e-02, -7.32066259e-02,  4.88667525e-02,
         4.98490967e-02, -9.01141204e-03, -4.68905605e-02,
        -4.25886884e-02, -8.19524452e-02,  3.87106277e-02,
         7.85504133e-02,  1.46077023e-32,  1.66706610e-02,
         5.25494255e-02, -1.82449669e-02, -1.26686813e-02,
         6.52836785e-02, -2.11777277e-02, -4.06323075e-02,
         4.14948687e-02, -2.48361714e-02, -1.33068226e-02,
        -5.46753481e-02, -5.99134248e-04, -4.89245635e-03,
        -6.27359673e-02, -3.84878591e-02, -6.13543428e-02,
         8.27404782e-02,  2.34380234e-02, -8.63084663e-03,
         1.31002404e-02,  6.44214228e-02, -4.41361256e-02,
        -6.98633343e-02, -7.36059994e-02, -4.33264486e-02,
         6.96518691e-03, -5.05957231e-02, -1.60911269e-02,
        -5.66794388e-02,  3.35452752e-03,  5.34115620e-02,
         2.47761980e-02, -1.47986831e-02, -2.93243006e-02,
         7.30229095e-02, -1.86833423e-02,  8.13137218e-02,
        -2.69967727e-02, -5.68055734e-02, -6.59388080e-02,
        -5.95394196e-03,  2.85312738e-02, -7.85357505e-02,
        -2.76690815e-03, -3.26480577e-03, -9.28333402e-02,
        -7.27363899e-02, -3.31903845e-02,  1.01411097e-01,
         9.79882032e-02, -9.78740230e-02,  1.98667739e-02,
         2.38837469e-02, -1.81672871e-02, -3.73708457e-02,
         1.96557911e-03,  6.34425506e-02,  1.18270852e-02,
        -1.12041179e-02, -3.87316272e-02,  9.32424814e-02,
         4.26630862e-03, -1.66872367e-02, -6.87464401e-02,
         1.55119123e-02, -4.97755073e-02,  3.34493555e-02,
         8.00032765e-02,  2.12282501e-02,  1.34581849e-01,
        -2.30729859e-02,  5.53858839e-02,  3.07557862e-02,
        -2.93905772e-02,  2.31905021e-02, -9.34307203e-02,
         7.58034736e-02, -5.21204202e-03, -5.14523052e-02,
         3.32689695e-02,  3.67963575e-02, -1.06450459e-02,
         1.01635866e-02, -2.07650717e-02, -5.85518703e-02,
         4.79328632e-02,  2.13694330e-02,  8.76212418e-02,
         3.35491844e-03, -3.80336605e-02, -1.81205384e-02,
         6.87446026e-03,  5.15878722e-02, -4.75599021e-02,
        -6.12064674e-02, -1.45483545e-32,  4.12803842e-03,
         4.59643779e-03, -5.63901365e-02,  4.32474259e-03,
        -1.09443592e-03,  9.31957085e-03, -2.20268611e-02,
         5.79565428e-02, -1.44787962e-02,  4.64156643e-02,
         1.43542945e-01, -6.89756498e-02,  6.09630793e-02,
        -8.93744528e-02,  2.40919534e-02,  2.06010230e-02,
        -2.82415431e-02, -6.48315996e-02,  5.64794987e-02,
        -7.48341857e-03, -3.52057666e-02,  8.51059929e-02,
         1.30359782e-02,  2.02257894e-02, -1.44390939e-02,
        -4.63718660e-02,  1.77209880e-02,  1.59105808e-02,
        -9.51009616e-02, -3.54527384e-02,  2.08696518e-02,
         3.84380599e-03, -8.77918005e-02,  6.44575432e-02,
         1.44170905e-02,  3.84735502e-03,  4.70991358e-02,
         4.94662151e-02,  1.53863207e-02, -2.59579308e-02,
         9.10894945e-02,  1.83307752e-02, -5.89206479e-02,
         2.51992960e-02, -3.30374278e-02,  8.23344290e-02,
         1.74792241e-02,  6.48047775e-02, -1.19674038e-02,
        -3.31778005e-02,  3.00177578e-02,  3.54220718e-02,
        -1.39624448e-02,  6.69272691e-02,  3.87919657e-02,
         6.06916510e-02,  1.17958791e-03, -2.38786619e-02,
        -1.26930431e-01,  1.13846781e-02,  1.59290489e-02,
        -1.29427053e-02, -8.63248035e-02,  8.53661448e-03,
         6.03761263e-02,  1.51122017e-02, -1.19132429e-01,
         1.15234675e-02,  5.97088933e-02, -3.93345244e-02,
         1.55673660e-02,  1.04602296e-02, -4.72457148e-02,
        -2.59243529e-02,  9.98522155e-03,  3.07146050e-02,
        -7.14843869e-02,  6.98963040e-03, -1.55133354e-02,
         2.18864121e-02, -2.78145391e-02,  6.92733750e-02,
        -2.75904350e-02,  2.62429174e-02,  3.52562517e-02,
        -4.26418371e-02,  7.46305450e-04,  6.59866929e-02,
        -5.15105054e-02, -3.58433649e-02, -6.53438736e-03,
        -2.75858119e-02, -1.00125566e-01,  7.83325583e-02,
        -1.45799592e-02, -6.18457179e-08,  2.00325679e-02,
         6.59785643e-02, -2.04702690e-02,  1.64044555e-02,
         7.63000995e-02,  7.32182860e-02,  5.65786613e-03,
        -6.97753916e-04, -3.63796344e-03,  6.02393784e-02,
        -3.27186882e-02, -6.45837858e-02, -5.97952530e-02,
        -1.76695809e-02,  6.10146113e-03, -5.63483546e-03,
        -1.22972220e-01,  6.35818467e-02, -2.19432097e-02,
        -1.16406456e-01,  2.34365389e-02, -7.23525211e-02,
         2.31773797e-02, -6.55987561e-02, -7.42682219e-02,
         2.60146093e-02,  3.59757245e-02,  7.68433064e-02,
        -3.08057219e-02, -2.34793685e-02, -6.30425885e-02,
        -3.62158231e-02, -1.03560416e-02, -4.75602634e-02,
        -2.87521854e-02,  2.96401158e-02, -5.26903663e-03,
         5.67888804e-02, -3.74489627e-03,  3.09612490e-02,
         3.48227657e-02,  3.78607549e-02,  2.10155696e-02,
         2.70691849e-02,  5.25520779e-02,  7.16229603e-02,
        -5.53750107e-03,  4.01093923e-02,  5.16276509e-02,
        -2.67314389e-02,  5.94224669e-02, -4.29223552e-02,
        -1.19760931e-02,  3.05985734e-02, -7.40331262e-02,
         1.84221286e-02, -8.64860974e-03, -8.83558244e-02,
        -5.91984428e-02, -1.00860976e-04,  1.12913601e-01,
         4.57789656e-03, -4.25971858e-02,  3.22622340e-03],
       [ 8.04573204e-03, -3.57392542e-02,  4.93873954e-02,
        -7.19196256e-03,  6.17648999e-04, -9.05684233e-02,
         5.75594865e-02, -4.39446010e-02,  1.74750984e-02,
         5.21202944e-02, -4.62332442e-02,  2.49039363e-02,
         4.80810814e-02,  6.86636120e-02,  3.56147438e-02,
         3.00088618e-02,  2.61450093e-02, -9.05241817e-02,
        -8.02173167e-02,  5.04850782e-02, -7.90871009e-02,
        -1.76851253e-03, -2.48927083e-02,  9.02152434e-02,
         5.83692594e-03, -6.91070855e-02, -6.67965412e-02,
        -6.99117873e-03, -1.04566030e-01, -2.66474001e-02,
         3.05640269e-02,  2.02934407e-02,  2.25453842e-02,
        -4.22683125e-03,  1.11173205e-02,  6.78260624e-02,
         1.06073776e-02,  7.56636336e-02, -8.22777823e-02,
         8.45731888e-03, -6.97611943e-02, -4.21974733e-02,
        -1.05675040e-02,  2.23673303e-02,  5.64497113e-02,
         8.16502608e-03,  1.09344013e-01,  3.16564888e-02,
        -1.76923480e-02, -3.21071893e-02, -3.39975804e-02,
        -4.91830171e-04,  3.72880022e-03,  2.83771865e-02,
        -1.28521277e-02, -1.07934570e-03, -6.32418916e-02,
         6.89900890e-02,  1.77270118e-02, -5.20958938e-02,
         8.28306377e-03,  5.45032583e-02, -5.42099476e-02,
        -4.53332737e-02, -4.07494046e-02, -2.82698292e-02,
         1.23605961e-02, -2.13816296e-02, -2.36265939e-02,
         1.25318095e-02, -2.37170793e-02,  3.97411287e-02,
        -1.24362297e-01,  7.60626048e-02,  5.50833344e-02,
         8.28216746e-02,  2.97119338e-02, -1.84067693e-02,
        -1.96194723e-02,  5.54319173e-02, -3.49144153e-02,
        -4.14677374e-02, -3.37047465e-02,  7.31324628e-02,
         4.41836827e-02,  2.55246144e-02, -8.26406013e-03,
        -1.07322866e-02, -4.26243730e-02, -2.84960470e-03,
         7.38558769e-02,  2.27769166e-02,  7.15377973e-04,
         4.36012596e-02,  5.09080030e-02,  6.38482422e-02,
        -2.73155943e-02, -6.55021518e-02, -7.69265071e-02,
         3.55171375e-02,  9.60494429e-02,  2.18195710e-02,
         1.20154722e-02, -1.17864069e-02, -4.57933173e-03,
        -8.58034566e-03,  3.37150246e-02,  2.31918301e-02,
        -7.58325607e-02, -5.23878634e-02,  4.53934036e-02,
        -3.80785652e-02, -3.34904417e-02,  9.20352638e-02,
         2.87689138e-02, -3.33817601e-02, -1.95848779e-03,
        -3.04560002e-04, -1.70499627e-02,  2.85336282e-02,
        -8.81096274e-02, -4.02252749e-02, -4.00093198e-02,
        -1.03192842e-02, -2.51968410e-02,  2.14093421e-02,
         1.31045252e-01, -5.29634821e-34, -1.09651722e-01,
         1.29811754e-02,  5.92656294e-03,  4.73506413e-02,
        -8.60295910e-03, -3.67089361e-02,  3.05214711e-02,
         5.53067178e-02, -4.71985340e-02, -1.25118727e-02,
        -1.15366451e-01,  9.08003189e-03,  1.07346505e-01,
        -4.94734645e-02, -1.34290950e-02, -4.61562537e-02,
         2.45320071e-02,  9.45080724e-03,  2.04324499e-02,
        -3.99918668e-02, -4.67826091e-02,  2.21171007e-02,
        -4.58186604e-02, -8.13270733e-03, -7.65665248e-03,
         1.92283932e-02,  4.85844761e-02, -2.55902782e-02,
         1.61545083e-03, -1.37180453e-02,  9.67306457e-03,
         7.36412592e-03,  1.14088422e-02,  1.28853455e-01,
         7.71838147e-03,  7.06362128e-02,  2.54451483e-02,
         4.06524092e-02,  2.44039241e-02,  1.43776620e-02,
        -6.00932278e-02,  7.38180652e-02, -2.44700927e-02,
         8.98901820e-02,  3.17047909e-03,  1.01834439e-01,
         4.17741761e-02, -5.95178120e-02, -3.23182121e-02,
         3.80938798e-02,  1.21156052e-02, -4.07834165e-02,
         2.84823030e-02,  4.90988381e-02, -9.35704634e-03,
         6.50073960e-02,  7.23532066e-02, -1.67793501e-02,
        -8.22419208e-03, -1.61573291e-02,  5.96226044e-02,
        -3.36084142e-02,  2.12108139e-02, -6.06090650e-02,
         1.54377669e-01, -7.24145994e-02, -3.77272516e-02,
        -3.26890610e-02, -1.80383516e-03, -1.01960367e-02,
        -1.60676811e-03, -6.91846833e-02,  8.28444809e-02,
         9.88839716e-02,  3.45475273e-03, -9.90247726e-02,
        -3.52826975e-02, -7.13179037e-02, -4.96000536e-02,
        -3.43955159e-02, -8.13041627e-02,  4.81447615e-02,
         5.00683952e-03, -2.21499596e-02, -5.60056865e-02,
         1.00067854e-02, -3.59793566e-02,  1.06184289e-01,
        -4.54196967e-02,  7.16393366e-02, -2.36772895e-02,
         9.98142082e-03,  2.73602400e-02,  1.05985448e-01,
         4.60164621e-02,  9.59028352e-34, -1.12306967e-01,
         2.78912652e-02, -3.35900784e-02,  5.39242215e-02,
        -2.22291443e-02,  1.53769162e-02,  3.10411528e-02,
         3.39010805e-02,  7.43167102e-02,  3.42470929e-02,
        -3.35056172e-03, -2.05351021e-02, -3.62370089e-02,
         2.29334477e-02, -3.01991981e-02, -1.00819938e-01,
         3.29194218e-02,  6.77543133e-02,  1.35645149e-02,
        -5.20549342e-03, -6.58158362e-02,  9.54550579e-02,
        -1.34038916e-02,  1.53885009e-02, -7.22936243e-02,
         9.67836082e-02, -8.08119923e-02, -4.53451555e-03,
        -6.42011240e-02, -4.99278791e-02,  4.64197211e-02,
         2.21340507e-02,  3.13109644e-02,  9.13568363e-02,
        -4.61120084e-02, -1.02761060e-01,  3.04415990e-02,
         5.09876125e-02,  6.70141205e-02,  1.04043027e-02,
         1.63533539e-02,  3.92030925e-02,  2.17154101e-02,
         5.36603890e-02,  3.62809487e-02, -4.22141030e-02,
        -2.47227401e-02,  1.90311875e-02,  3.61723863e-02,
         6.37021661e-02, -3.21582821e-03, -8.50391202e-03,
         3.94655578e-02,  9.02650412e-03,  1.93095803e-02,
         6.60718083e-02,  1.02694845e-02, -4.43853885e-02,
        -1.56523138e-02, -1.55713689e-02,  1.32904155e-02,
        -1.16108358e-02,  4.21832204e-02, -5.44776507e-02,
         1.29237160e-01, -2.25757156e-02,  5.26204184e-02,
        -1.58437323e-02,  9.33165252e-02,  6.38024881e-03,
        -9.36160982e-03, -6.08875565e-02, -3.27307768e-02,
        -3.44817042e-02,  3.29974294e-02, -4.79391627e-02,
        -9.81301144e-02,  2.91165542e-02, -2.70903185e-02,
         1.81866977e-02, -1.73860528e-02, -4.40371595e-02,
        -7.97002465e-02,  3.01647391e-02, -6.35260269e-02,
         1.25963064e-02,  8.50249827e-02, -4.58910465e-02,
         5.81017733e-02, -2.71002408e-02,  8.42776224e-02,
        -4.09972817e-02, -3.37656066e-02,  1.02088423e-02,
        -2.54192911e-02, -1.40610252e-08,  4.94446754e-02,
        -9.04356614e-02, -6.06709979e-02,  8.29529911e-02,
        -3.29032652e-02,  4.14910801e-02,  9.99595039e-03,
         6.96134102e-03,  3.99237638e-03, -3.24333273e-02,
        -3.14656682e-02, -5.33161610e-02, -3.80912982e-02,
         1.62076429e-02,  2.45779175e-02, -7.26419166e-02,
        -6.56893328e-02, -8.23131725e-02, -8.00500959e-02,
        -5.36648855e-02,  5.60894832e-02, -1.10913049e-02,
         9.62128513e-04, -1.22690298e-01, -5.13837151e-02,
         9.96704772e-03,  1.00696217e-02,  1.07073084e-01,
         1.19758192e-02,  1.00423526e-02, -6.28261790e-02,
        -7.49696717e-02, -6.34076027e-03, -2.72201188e-02,
        -1.28096238e-01, -2.62459945e-02, -1.81464851e-02,
        -9.85359997e-02, -3.02990302e-02, -4.02614735e-02,
         9.94291008e-02,  5.35999686e-02,  2.74899229e-02,
        -5.53682446e-03,  8.43570828e-02,  8.35161731e-02,
         3.74304317e-02,  7.11937249e-02,  2.98902951e-02,
         2.32728794e-02, -3.62112634e-02,  6.20540194e-02,
         2.15147901e-02,  5.19732572e-02,  1.45337917e-02,
        -4.60967086e-02,  5.02554476e-02, -7.27027953e-02,
         2.92779021e-02,  5.62662967e-02, -3.86355519e-02,
         1.53831569e-02, -6.23095557e-02, -2.77466401e-02]], dtype=float32)

In [45]:
X = filtered_embeddings 
y = df_non_legacy['target_label']

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression 
from sklearn.metrics import classification_report

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)
clf = LogisticRegression(max_iter = 1000)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
report = classification_report(y_test, y_pred)
print(report)

                precision    recall  f1-score   support

Critical Error       0.91      1.00      0.95        48
         Error       0.98      0.89      0.93        47
   HTTP Status       1.00      1.00      1.00       304
Resource Usage       1.00      1.00      1.00        49
Security Alert       1.00      0.99      1.00       123

      accuracy                           0.99       571
     macro avg       0.98      0.98      0.98       571
  weighted avg       0.99      0.99      0.99       571

In [ ]:
import joblib

joblib.dump(clf, '../models/log_classifier.joblib')

['models/log_classifier.joblib']